import type { CatalogResource, Difficulty, ResourceType } from './types';

type Row = [
	slug: string,
	title: string,
	url: string,
	provider: string,
	type: ResourceType,
	difficulty: Difficulty,
	cost: CatalogResource['cost'],
	minutes: number,
	description: string,
	why: string,
	tags: string[]
];

/**
 * Curated library. Every URL is a real public page verified with
 * `bun run links:check`. Descriptions are editorial — no invented ratings or reviews.
 */
const ROWS: Row[] = [
	// Web foundations
	['mdn-http-overview', 'An overview of HTTP', 'https://developer.mozilla.org/en-US/docs/Web/HTTP/Overview', 'MDN Web Docs', 'documentation', 1, 'free', 25, 'How clients and servers talk: requests, responses, headers and the stateless model.', 'The clearest short explanation of what happens when a page loads.', ['web', 'http']],
	['cloudflare-learning', 'Cloudflare Learning Center', 'https://www.cloudflare.com/learning/', 'Cloudflare', 'article', 1, 'free', 40, 'Plain-language explainers on DNS, CDNs, TLS and how the internet routes traffic.', 'Fills gaps about DNS and HTTPS without academic depth.', ['web', 'networking']],
	['mdn-learn-html', 'MDN: Structuring content with HTML', 'https://developer.mozilla.org/en-US/docs/Learn/HTML', 'MDN Web Docs', 'tutorial', 1, 'free', 240, 'The canonical beginner module for semantic HTML, forms, media and document structure.', 'Teaches semantics first, which makes accessibility and CSS easier later.', ['html']],
	['webdev-learn-html', 'Learn HTML', 'https://web.dev/learn/html', 'web.dev (Google)', 'course', 1, 'free', 300, 'A modern, example-driven HTML course covering semantics, forms and metadata.', 'A well-paced alternative to MDN focused on real page structure.', ['html']],
	['mdn-learn-css', 'MDN: CSS styling basics', 'https://developer.mozilla.org/en-US/docs/Learn/CSS', 'MDN Web Docs', 'tutorial', 1, 'free', 300, 'Selectors, the cascade, the box model and styling text from first principles.', 'Explains why CSS behaves the way it does.', ['css']],
	['webdev-learn-css', 'Learn CSS', 'https://web.dev/learn/css', 'web.dev (Google)', 'course', 2, 'free', 480, 'From the box model through layout, custom properties and logical properties.', 'The best free resource for a durable mental model of modern CSS.', ['css']],
	['css-tricks-flexbox', 'A Complete Guide to Flexbox', 'https://css-tricks.com/snippets/css/a-guide-to-flexbox/', 'CSS-Tricks', 'article', 2, 'free', 30, 'Visual reference for every flex container and flex item property.', 'The reference most developers keep open while building layouts.', ['css', 'flexbox']],
	['css-tricks-grid', 'CSS Grid Layout Guide', 'https://css-tricks.com/snippets/css/complete-guide-grid/', 'CSS-Tricks', 'article', 2, 'free', 35, 'Visual reference for grid containers, tracks, areas and alignment.', 'Pairs well with hands-on practice to make grid click.', ['css', 'grid']],
	['flexbox-froggy', 'Flexbox Froggy', 'https://flexboxfroggy.com/', 'Codepip', 'interactive', 1, 'free', 30, 'A short game where you position frogs with flexbox properties.', 'Builds muscle memory for justify/align in a way reading cannot.', ['css', 'flexbox']],
	['webdev-responsive', 'Responsive web design basics', 'https://web.dev/articles/responsive-web-design-basics', 'web.dev (Google)', 'article', 2, 'free', 25, 'Viewport meta, fluid layouts, media queries and responsive images.', 'Covers the few techniques that handle most responsive work.', ['css', 'responsive']],
	['frontend-mentor', 'Frontend Mentor challenges', 'https://www.frontendmentor.io/', 'Frontend Mentor', 'project', 2, 'freemium', 240, 'Realistic design files to rebuild as working, responsive pages.', 'Turns layout knowledge into portfolio work against a real spec.', ['html', 'css', 'projects']],
	['webdev-accessibility', 'Learn Accessibility', 'https://web.dev/learn/accessibility', 'web.dev (Google)', 'course', 2, 'free', 300, 'ARIA, focus management, color contrast and assistive technology basics.', 'Practical, developer-focused accessibility.', ['accessibility']],
	['wcag-quickref', 'How to Meet WCAG (Quick Reference)', 'https://www.w3.org/WAI/WCAG22/quickref/', 'W3C WAI', 'documentation', 3, 'free', 45, 'The official, filterable checklist of WCAG success criteria and techniques.', 'The authoritative source for whether something passes.', ['accessibility']],
	// Tooling
	['missing-semester-shell', 'The Missing Semester: the shell', 'https://missing.csail.mit.edu/2020/course-shell/', 'MIT CSAIL', 'course', 1, 'free', 60, 'A lecture and notes introducing the shell, paths, pipes and permissions.', 'Teaches the terminal as a tool you think with.', ['cli']],
	['missing-semester', 'The Missing Semester of Your CS Education', 'https://missing.csail.mit.edu/', 'MIT CSAIL', 'course', 2, 'free', 600, 'Shell, scripting, editors, version control, debugging and more.', 'Covers the tooling fluency courses assume you have.', ['cli', 'git']],
	['pro-git', 'Pro Git (book)', 'https://git-scm.com/book/en/v2', 'git-scm.com', 'book', 2, 'free', 480, 'The official Git book: basics through branching, remotes and internals.', 'Chapters 1–3 give you a correct model of commits and branches.', ['git']],
	['learn-git-branching', 'Learn Git Branching', 'https://learngitbranching.js.org/', 'learngitbranching.js.org', 'interactive', 1, 'free', 90, 'Visual, interactive levels for commits, branches, merges and rebases.', 'Seeing the commit graph change removes the fear of Git.', ['git']],
	['npm-docs', 'About npm', 'https://docs.npmjs.com/about-npm', 'npm Docs', 'documentation', 1, 'free', 20, 'What the registry, CLI and package.json are and how they fit together.', 'Clarifies dependencies and semantic versioning.', ['javascript', 'tooling']],
	['vite-guide', 'Vite: Getting Started', 'https://vite.dev/guide/', 'Vite', 'documentation', 2, 'free', 30, 'Why modern build tools exist and how Vite serves and bundles modules.', 'Demystifies dev servers, bundling and HMR.', ['javascript', 'tooling']],
	// JavaScript & TypeScript
	['javascript-info', 'The Modern JavaScript Tutorial', 'https://javascript.info/', 'javascript.info', 'tutorial', 2, 'free', 1200, 'A carefully sequenced tutorial from basics to advanced language features.', 'Each chapter ends with tasks, so reading turns into practice.', ['javascript']],
	['mdn-js-guide', 'MDN JavaScript Guide', 'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide', 'MDN Web Docs', 'documentation', 2, 'free', 480, 'Grammar, types, control flow, functions, objects and more.', 'The reference for precise language behaviour.', ['javascript']],
	['javascript-info-closure', 'Variable scope, closure', 'https://javascript.info/closure', 'javascript.info', 'tutorial', 3, 'free', 40, 'Lexical environments explained step by step with diagrams.', 'Shows exactly how closures capture variables.', ['javascript', 'closures']],
	['mdn-closures', 'MDN: Closures', 'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Closures', 'MDN Web Docs', 'documentation', 3, 'free', 25, 'Lexical scoping, practical closures and the classic loop pitfall.', 'A concise second angle on closures.', ['javascript', 'closures']],
	['mdn-dom-intro', 'Introduction to the DOM', 'https://developer.mozilla.org/en-US/docs/Web/API/Document_Object_Model/Introduction', 'MDN Web Docs', 'documentation', 2, 'free', 25, 'How the browser represents a page as a tree you can read and modify.', 'The foundation for every UI framework.', ['javascript', 'dom']],
	['javascript30', 'JavaScript30', 'https://javascript30.com/', 'Wes Bos', 'video', 2, 'free', 900, '30 small vanilla JavaScript projects built on video.', 'DOM and events practice through tiny, finishable builds.', ['javascript', 'projects']],
	['javascript-info-async', 'Promises, async/await', 'https://javascript.info/async', 'javascript.info', 'tutorial', 3, 'free', 120, 'Callbacks, promises, chaining, error handling and async/await.', 'Builds async understanding in the right order.', ['javascript', 'async']],
	['mdn-promises', 'MDN: Using promises', 'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Using_promises', 'MDN Web Docs', 'documentation', 3, 'free', 30, 'Chaining, error propagation, composition and timing of promises.', 'Precise explanations of tricky edge cases.', ['javascript', 'async']],
	['mdn-fetch', 'MDN: Using the Fetch API', 'https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch', 'MDN Web Docs', 'documentation', 2, 'free', 25, 'Making HTTP requests from the browser, handling JSON and errors.', 'Connects async JavaScript to real network calls.', ['javascript', 'http']],
	['mdn-js-modules', 'MDN: JavaScript modules', 'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules', 'MDN Web Docs', 'documentation', 2, 'free', 30, 'import/export, module scope, dynamic imports and module loading.', 'The module system every modern toolchain builds on.', ['javascript']],
	['eloquent-javascript', 'Eloquent JavaScript (4th edition)', 'https://eloquentjavascript.net/', 'Marijn Haverbeke', 'book', 3, 'free', 1500, 'A thoughtful book on programming through JavaScript, with exercises.', 'Develops deeper programming thinking.', ['javascript']],
	['exercism-javascript', 'Exercism JavaScript track', 'https://exercism.org/tracks/javascript', 'Exercism', 'exercise', 2, 'free', 600, 'Concept exercises and practice problems with optional mentoring.', 'Small test-driven exercises for each concept.', ['javascript', 'practice']],
	['ts-handbook', 'The TypeScript Handbook', 'https://www.typescriptlang.org/docs/handbook/intro.html', 'TypeScript', 'documentation', 2, 'free', 300, 'Everyday types, narrowing, generics and object types.', 'Official, current and practical.', ['typescript']],
	['exercism-typescript', 'Exercism TypeScript track', 'https://exercism.org/tracks/typescript', 'Exercism', 'exercise', 2, 'free', 480, 'Typed practice exercises with automated tests.', 'Forces you to model data with types.', ['typescript', 'practice']],
	['ts-playground', 'TypeScript Playground', 'https://www.typescriptlang.org/play', 'TypeScript', 'interactive', 1, 'free', 30, 'An in-browser editor showing type errors and emitted JavaScript.', 'Instant feedback for experimenting with types.', ['typescript']],
	// Frontend
	['svelte-tutorial', 'Svelte interactive tutorial', 'https://svelte.dev/tutorial', 'Svelte', 'interactive', 2, 'free', 240, 'Components, reactivity with runes, props, events and bindings.', 'The gentlest hands-on introduction to component thinking.', ['frontend', 'svelte']],
	['react-learn', 'React: Learn', 'https://react.dev/learn', 'React', 'documentation', 2, 'free', 360, 'Thinking in components, state, effects and data flow.', 'Excellent conceptual writing on UI as a function of state.', ['frontend', 'react']],
	['vue-guide', 'Vue.js Guide', 'https://vuejs.org/guide/introduction.html', 'Vue.js', 'documentation', 2, 'free', 300, 'Reactivity, components and the Vue ecosystem explained progressively.', 'Another clear perspective on reactivity.', ['frontend', 'vue']],
	['vitest-guide', 'Vitest: Getting Started', 'https://vitest.dev/guide/', 'Vitest', 'documentation', 2, 'free', 40, 'Writing and running unit tests with a fast, Vite-native runner.', 'Minimal setup, so time goes into test design.', ['testing']],
	['testing-library', 'Testing Library docs', 'https://testing-library.com/docs/', 'Testing Library', 'documentation', 3, 'free', 60, 'Testing UI the way users interact with it: by role, label and text.', 'The principle behind resilient UI tests.', ['testing']],
	['playwright-intro', 'Playwright: Getting started', 'https://playwright.dev/docs/intro', 'Playwright', 'documentation', 3, 'free', 60, 'End-to-end browser testing with auto-waiting locators.', 'The modern standard for testing user journeys.', ['testing']],
	['webdev-performance', 'Learn Performance', 'https://web.dev/learn/performance', 'web.dev (Google)', 'course', 3, 'free', 300, 'Critical rendering path, resource hints, images and code splitting.', 'Connects techniques to what the browser does.', ['performance']],
	['webdev-vitals', 'Web Vitals', 'https://web.dev/articles/vitals', 'web.dev (Google)', 'article', 2, 'free', 20, 'LCP, INP and CLS: what they measure and good thresholds.', 'The vocabulary and targets for measuring UX.', ['performance']],
	// Full-stack curricula
	['full-stack-open', 'Full Stack Open', 'https://fullstackopen.com/en/', 'University of Helsinki', 'course', 3, 'free', 6000, 'University-grade course on modern web apps: frontend, Node, testing, CI.', 'Rigorous and covers testing and deployment properly.', ['fullstack', 'node']],
	['freecodecamp', 'freeCodeCamp curriculum', 'https://www.freecodecamp.org/learn', 'freeCodeCamp', 'interactive', 1, 'free', 6000, 'Interactive lessons and certification projects across web and data.', 'In-browser practice with instant feedback.', ['fullstack']],
	// Backend & databases
	['mdn-http-methods', 'MDN: HTTP request methods', 'https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods', 'MDN Web Docs', 'documentation', 2, 'free', 20, 'GET, POST, PUT, PATCH, DELETE: semantics, safety and idempotency.', 'Essential for predictable APIs.', ['http', 'api']],
	['node-learn', 'Learn Node.js', 'https://nodejs.org/en/learn', 'Node.js', 'documentation', 2, 'free', 240, 'The official introduction: event loop, modules, file system and HTTP.', 'The runtime model behind JavaScript backends.', ['node', 'backend']],
	['express-guide', 'Express: Getting started', 'https://expressjs.com/en/starter/installing.html', 'Express', 'documentation', 2, 'free', 60, 'Routing, middleware and responses with the classic Node framework.', 'Middleware concepts transfer to every framework.', ['node', 'api']],
	['postgres-tutorial', 'PostgreSQL Tutorial (official)', 'https://www.postgresql.org/docs/current/tutorial.html', 'PostgreSQL', 'documentation', 2, 'free', 120, 'Creating tables, querying, joins, aggregates and transactions.', 'Short, authoritative and production-relevant.', ['sql', 'postgres']],
	['sqlbolt', 'SQLBolt', 'https://sqlbolt.com/', 'SQLBolt', 'interactive', 1, 'free', 120, 'Interactive lessons with exercises from SELECT to JOINs and aggregates.', 'The fastest way to get comfortable with queries.', ['sql']],
	['pg-exercises', 'PostgreSQL Exercises', 'https://pgexercises.com/', 'pgexercises.com', 'exercise', 3, 'free', 240, 'Graded SQL problems on a realistic schema.', 'Deliberate practice for joins and aggregates.', ['sql', 'practice']],
	['drizzle-docs', 'Drizzle ORM docs', 'https://orm.drizzle.team/docs/overview', 'Drizzle', 'documentation', 3, 'free', 90, 'A SQL-like TypeScript ORM: schemas, queries, relations and migrations.', 'Stays close to SQL with type safety.', ['orm', 'sql']],
	['owasp-top-ten', 'OWASP Top Ten', 'https://owasp.org/www-project-top-ten/', 'OWASP', 'documentation', 3, 'free', 60, 'The most critical web application security risks and prevention.', 'The shared vocabulary for web security.', ['security']],
	['owasp-auth-cheatsheet', 'OWASP Authentication Cheat Sheet', 'https://cheatsheetseries.owasp.org/cheatsheets/Authentication_Cheat_Sheet.html', 'OWASP', 'documentation', 3, 'free', 40, 'Password storage, login flows, error messages and MFA guidance.', 'Concrete rules for your own auth code.', ['security', 'auth']],
	['owasp-session-cheatsheet', 'OWASP Session Management Cheat Sheet', 'https://cheatsheetseries.owasp.org/cheatsheets/Session_Management_Cheat_Sheet.html', 'OWASP', 'documentation', 3, 'free', 40, 'Session IDs, cookie attributes, expiry and fixation defences.', 'Why HttpOnly, Secure and SameSite matter.', ['security', 'auth']],
	['docker-get-started', 'Docker: Get started', 'https://docs.docker.com/get-started/', 'Docker', 'tutorial', 2, 'free', 120, 'Images, containers, Dockerfiles and multi-service apps.', 'Makes environments reproducible.', ['devops']],
	['github-actions', 'GitHub Actions documentation', 'https://docs.github.com/en/actions', 'GitHub', 'documentation', 2, 'free', 60, 'Workflows, jobs and steps for automated testing and deployment.', 'The simplest way to add CI.', ['devops', 'ci']],
	['twelve-factor', 'The Twelve-Factor App', 'https://12factor.net/', '12factor.net', 'article', 3, 'free', 45, 'Principles for config, dependencies, processes and logs.', 'Why env vars and stateless processes matter.', ['devops']],
	['system-design-primer', 'The System Design Primer', 'https://github.com/donnemartin/system-design-primer', 'GitHub (donnemartin)', 'article', 4, 'free', 600, 'Caching, load balancing, databases, queues and trade-offs.', 'A well-organised map of system design.', ['system-design']],
	['ddia-book', 'Designing Data-Intensive Applications', 'https://dataintensive.net/', 'Martin Kleppmann', 'book', 5, 'paid', 1800, 'Reliability, scalability and maintainability of data systems.', 'The definitive book on data systems.', ['system-design']],
	// CS core
	['cs50x', 'CS50x: Introduction to Computer Science', 'https://cs50.harvard.edu/x/', 'Harvard University', 'course', 2, 'free', 6000, 'Lectures and problem sets covering C, Python, SQL, algorithms and memory.', 'The best free broad introduction to computing.', ['cs']],
	['visualgo', 'VisuAlgo', 'https://visualgo.net/en', 'NUS', 'interactive', 2, 'free', 120, 'Animated visualisations of data structures and algorithms.', 'Step-by-step animation builds intuition.', ['algorithms']],
	['open-data-structures', 'Open Data Structures', 'https://opendatastructures.org/', 'Pat Morin', 'book', 3, 'free', 1200, 'An open textbook on lists, trees, heaps, hashing and graphs.', 'Rigorous but readable.', ['data-structures']],
	['mit-6006', 'MIT 6.006 Introduction to Algorithms', 'https://ocw.mit.edu/courses/6-006-introduction-to-algorithms-spring-2020/', 'MIT OpenCourseWare', 'course', 4, 'free', 3000, 'Lectures, notes and problem sets on algorithm design and analysis.', 'University depth on algorithms.', ['algorithms']],
	['neetcode-roadmap', 'NeetCode Roadmap', 'https://neetcode.io/roadmap', 'NeetCode', 'exercise', 3, 'freemium', 1200, 'Problems grouped by pattern.', 'Practice organised by pattern.', ['algorithms', 'practice']],
	['bigo-cheatsheet', 'Big-O Cheat Sheet', 'https://www.bigocheatsheet.com/', 'bigocheatsheet.com', 'article', 2, 'free', 15, 'Time and space complexity of common operations and sorts.', 'Handy while reasoning about choices.', ['algorithms']],
	['ostep', 'Operating Systems: Three Easy Pieces', 'https://pages.cs.wisc.edu/~remzi/OSTEP/', 'Arpaci-Dusseau (UW–Madison)', 'book', 3, 'free', 1800, 'Virtualisation, concurrency and persistence explained clearly.', 'The most approachable serious OS book.', ['os']],
	['beej-networking', 'Beej’s Guide to Network Programming', 'https://beej.us/guide/bgnet/', 'Brian “Beej” Hall', 'book', 3, 'free', 480, 'Sockets, TCP/UDP and client/server programming.', 'Makes networking concrete.', ['networking']],
	// Python & data
	['python-tutorial', 'The Python Tutorial (official)', 'https://docs.python.org/3/tutorial/', 'Python Software Foundation', 'documentation', 1, 'free', 480, 'Data types, control flow, functions, modules, errors and classes.', 'The best reference for core Python.', ['python']],
	['python-classes', 'Python Tutorial: Classes', 'https://docs.python.org/3/tutorial/classes.html', 'Python Software Foundation', 'documentation', 2, 'free', 45, 'Namespaces, class objects, inheritance and iterators.', 'How Python objects really work.', ['python']],
	['automate-boring-stuff', 'Automate the Boring Stuff with Python', 'https://automatetheboringstuff.com/', 'Al Sweigart', 'book', 1, 'free', 1200, 'Practical Python for automating files, spreadsheets and the web.', 'Every chapter produces something useful.', ['python', 'projects']],
	['exercism-python', 'Exercism Python track', 'https://exercism.org/tracks/python', 'Exercism', 'exercise', 2, 'free', 600, 'Concept exercises and practice problems with automated tests.', 'Deliberate practice for idiomatic Python.', ['python', 'practice']],
	['numpy-beginners', 'NumPy: the absolute basics for beginners', 'https://numpy.org/doc/stable/user/absolute_beginners.html', 'NumPy', 'documentation', 2, 'free', 60, 'Arrays, shapes, indexing, broadcasting and basic operations.', 'Covers exactly what data work needs.', ['python', 'data']],
	['pandas-10min', '10 minutes to pandas', 'https://pandas.pydata.org/docs/user_guide/10min.html', 'pandas', 'documentation', 2, 'free', 45, 'A tour of Series, DataFrames, selection, grouping and merging.', 'The fastest orientation to pandas.', ['python', 'data']],
	['kaggle-pandas', 'Kaggle Learn: Pandas', 'https://www.kaggle.com/learn/pandas', 'Kaggle', 'interactive', 2, 'free', 240, 'Exercises on indexing, grouping, sorting and combining data.', 'Practice on real datasets.', ['python', 'data', 'practice']],
	['kaggle-dataviz', 'Kaggle Learn: Data Visualization', 'https://www.kaggle.com/learn/data-visualization', 'Kaggle', 'interactive', 2, 'free', 240, 'Line, bar, heatmap, scatter and distribution plots with seaborn.', 'Teaches choosing the right chart.', ['python', 'visualization']],
	['seaborn-tutorial', 'seaborn user guide and tutorial', 'https://seaborn.pydata.org/tutorial.html', 'seaborn', 'documentation', 2, 'free', 90, 'Relational, distribution and categorical statistical plots.', 'Quick, correct exploratory charts.', ['python', 'visualization']],
	['khan-statistics', 'Khan Academy: Statistics and probability', 'https://www.khanacademy.org/math/statistics-probability', 'Khan Academy', 'course', 1, 'free', 1800, 'Distributions, probability, sampling, inference and regression.', 'Patient explanations with lots of practice.', ['statistics']],
	['seeing-theory', 'Seeing Theory', 'https://seeing-theory.brown.edu/', 'Brown University', 'interactive', 2, 'free', 90, 'An interactive visual introduction to probability and statistics.', 'Makes sampling distributions visible.', ['statistics']],
	['openintro-stats', 'OpenIntro Statistics', 'https://www.openintro.org/book/os/', 'OpenIntro', 'book', 2, 'free', 1500, 'A free, widely used introductory statistics textbook.', 'Rigorous foundations with real data.', ['statistics']],
	// AI & ML
	['3b1b-linear-algebra', 'Essence of Linear Algebra', 'https://www.3blue1brown.com/topics/linear-algebra', '3Blue1Brown', 'video', 2, 'free', 200, 'Visual intuition for vectors, matrices, transformations and eigenvectors.', 'Geometric intuition for ML math.', ['math', 'ml']],
	['mit-1806', 'MIT 18.06 Linear Algebra', 'https://ocw.mit.edu/courses/18-06-linear-algebra-spring-2010/', 'MIT OpenCourseWare', 'course', 4, 'free', 2400, 'Gilbert Strang’s classic lectures with problem sets.', 'The rigorous follow-up.', ['math']],
	['google-ml-crash-course', 'Machine Learning Crash Course', 'https://developers.google.com/machine-learning/crash-course', 'Google', 'course', 2, 'free', 900, 'Regression, classification, embeddings and responsible ML.', 'Compact and practical.', ['ml']],
	['kaggle-intro-ml', 'Kaggle Learn: Intro to Machine Learning', 'https://www.kaggle.com/learn/intro-to-machine-learning', 'Kaggle', 'interactive', 2, 'free', 180, 'Build and validate your first models with scikit-learn.', 'Training models within an hour.', ['ml', 'practice']],
	['sklearn-getting-started', 'scikit-learn: Getting Started', 'https://scikit-learn.org/stable/getting_started.html', 'scikit-learn', 'documentation', 2, 'free', 30, 'Estimators, pipelines, cross-validation and parameter search.', 'Core API patterns for ML projects.', ['ml']],
	['sklearn-model-evaluation', 'scikit-learn: Metrics and scoring', 'https://scikit-learn.org/stable/modules/model_evaluation.html', 'scikit-learn', 'documentation', 3, 'free', 60, 'Classification, regression and ranking metrics.', 'The right metric matters as much as the model.', ['ml']],
	['sklearn-cross-validation', 'scikit-learn: Cross-validation', 'https://scikit-learn.org/stable/modules/cross_validation.html', 'scikit-learn', 'documentation', 3, 'free', 40, 'Train/test splits, k-fold and avoiding data leakage.', 'Prevents fooling yourself.', ['ml']],
	['kaggle-intermediate-ml', 'Kaggle Learn: Intermediate Machine Learning', 'https://www.kaggle.com/learn/intermediate-machine-learning', 'Kaggle', 'interactive', 3, 'free', 240, 'Missing values, categorical variables, pipelines and leakage.', 'Messy-data skills real projects need.', ['ml', 'practice']],
	['3b1b-neural-networks', 'Neural Networks series', 'https://www.3blue1brown.com/topics/neural-networks', '3Blue1Brown', 'video', 2, 'free', 120, 'Neurons, gradient descent, backprop and transformers, visually.', 'Intuition-first introduction.', ['ml', 'deep-learning']],
	['karpathy-zero-to-hero', 'Neural Networks: Zero to Hero', 'https://karpathy.ai/zero-to-hero.html', 'Andrej Karpathy', 'video', 4, 'free', 900, 'Build backprop, language models and a GPT from scratch.', 'Implementing it yourself.', ['deep-learning', 'llm']],
	['fastai-course', 'Practical Deep Learning for Coders', 'https://course.fast.ai/', 'fast.ai', 'course', 3, 'free', 1800, 'Top-down deep learning: train real models first.', 'Working results quickly.', ['deep-learning']],
	['pytorch-tutorials', 'PyTorch Tutorials', 'https://pytorch.org/tutorials/', 'PyTorch', 'tutorial', 3, 'free', 600, 'Official tutorials from tensors and autograd to training loops.', 'Authoritative runnable examples.', ['deep-learning']],
	['illustrated-transformer', 'The Illustrated Transformer', 'https://jalammar.github.io/illustrated-transformer/', 'Jay Alammar', 'article', 3, 'free', 40, 'Attention and the transformer architecture with diagrams.', 'The standard visual walkthrough.', ['llm']],
	['hf-llm-course', 'Hugging Face LLM Course', 'https://huggingface.co/learn/llm-course', 'Hugging Face', 'course', 3, 'free', 900, 'Transformers, tokenizers, fine-tuning and open models.', 'Hands-on with open LLM tooling.', ['llm']],
	['prompting-guide', 'Prompt Engineering Guide', 'https://www.promptingguide.ai/', 'DAIR.AI', 'article', 2, 'free', 90, 'Prompting techniques, RAG, agents and model behaviour.', 'Broad practical coverage.', ['llm']],
	['ai-sdk-docs', 'AI SDK documentation', 'https://ai-sdk.dev/docs/introduction', 'Vercel', 'documentation', 3, 'free', 60, 'Streaming text, structured output and tool calling.', 'Provider-agnostic LLM features in TypeScript.', ['llm']],
	['pgvector', 'pgvector', 'https://github.com/pgvector/pgvector', 'GitHub (pgvector)', 'documentation', 3, 'free', 30, 'Vector similarity search inside PostgreSQL.', 'Semantic search without a vector database.', ['llm', 'postgres']],
	// Design
	['laws-of-ux', 'Laws of UX', 'https://lawsofux.com/', 'Jon Yablonski', 'article', 1, 'free', 60, 'Psychological principles like Fitts’s, Hick’s and Jakob’s law.', 'Reasons behind design decisions.', ['design', 'ux']],
	['nng-heuristics', '10 Usability Heuristics for User Interface Design', 'https://www.nngroup.com/articles/ten-usability-heuristics/', 'Nielsen Norman Group', 'article', 1, 'free', 20, 'Nielsen’s classic principles for interaction design.', 'A durable evaluation checklist.', ['design', 'ux']],
	['refactoring-ui', 'Refactoring UI', 'https://www.refactoringui.com/', 'Adam Wathan & Steve Schoger', 'book', 2, 'paid', 360, 'Tactical UI advice: hierarchy, spacing, color, depth.', 'Immediately actionable techniques.', ['design', 'ui']],
	['practical-typography', 'Practical Typography', 'https://practicaltypography.com/', 'Matthew Butterick', 'book', 2, 'free', 240, 'Typography rules for body text, headings and layout.', 'Short rules that improve text-heavy UI.', ['design', 'typography']],
	['material-color', 'Material Design 3: Color', 'https://m3.material.io/styles/color/overview', 'Google', 'documentation', 2, 'free', 40, 'Color roles, tonal palettes, contrast and dynamic color.', 'Color as a system.', ['design', 'color']],
	['apple-hig', 'Human Interface Guidelines', 'https://developer.apple.com/design/human-interface-guidelines', 'Apple', 'documentation', 2, 'free', 240, 'Guidance on layout, typography, color and interaction.', 'How a mature system reasons.', ['design', 'ui']],
	['nng-user-interviews', 'User Interviews 101', 'https://www.nngroup.com/articles/user-interviews/', 'Nielsen Norman Group', 'article', 2, 'free', 20, 'Planning, conducting and analysing user interviews.', 'Avoid leading questions and bias.', ['ux', 'research']],
	['google-ux-certificate', 'Google UX Design Professional Certificate', 'https://www.coursera.org/professional-certificates/google-ux-design', 'Google (Coursera)', 'course', 1, 'freemium', 9000, 'Research, wireframes, prototypes and testing end to end.', 'Structured beginner path.', ['ux', 'design']],
	['figma-learn', 'Figma: Learn design', 'https://www.figma.com/resources/learn-design/', 'Figma', 'tutorial', 1, 'free', 180, 'Design fundamentals and hands-on lessons inside Figma.', 'Tool and principles together.', ['design', 'figma']],
	['atomic-design', 'Atomic Design', 'https://atomicdesign.bradfrost.com/', 'Brad Frost', 'book', 3, 'free', 300, 'Building design systems from atoms to pages.', 'The model most design systems use.', ['design']],
	// Product & business
	['yc-library', 'Y Combinator Startup Library', 'https://www.ycombinator.com/library', 'Y Combinator', 'video', 2, 'free', 600, 'Talks and essays on ideas, users, growth and product.', 'First-hand startup advice.', ['business', 'product']],
	['yc-talk-to-users', 'How to talk to users', 'https://www.ycombinator.com/library/Iq-how-to-talk-to-users', 'Y Combinator', 'video', 1, 'free', 30, 'Why and how to interview customers without leading them.', 'The key early discovery skill.', ['business', 'research']],
	['mom-test', 'The Mom Test', 'https://www.momtestbook.com/', 'Rob Fitzpatrick', 'book', 1, 'paid', 180, 'Asking questions nobody can lie to you about.', 'Changes how you validate ideas.', ['business', 'research']],
	['pg-essays', 'Paul Graham’s essays', 'https://paulgraham.com/articles.html', 'Paul Graham', 'article', 2, 'free', 600, 'Essays on startups, ideas, growth and great work.', 'Sharp thinking on products.', ['business']],
	['business-model-canvas', 'The Business Model Canvas', 'https://www.strategyzer.com/library/the-business-model-canvas', 'Strategyzer', 'article', 2, 'free', 20, 'A one-page tool for how a business creates and captures value.', 'Forces clarity about the model.', ['business']],
	['north-star-playbook', 'The North Star Playbook', 'https://amplitude.com/books/north-star', 'Amplitude', 'book', 2, 'free', 120, 'Choosing a North Star metric and its inputs.', 'Connects metrics to value.', ['product', 'metrics']],
	['svpg-inspired', 'Inspired (2nd edition)', 'https://www.svpg.com/books/inspired-how-to-create-tech-products-customers-love-2nd-edition/', 'Marty Cagan (SVPG)', 'book', 2, 'paid', 600, 'How strong product teams discover and deliver products.', 'The standard PM reference.', ['product']]
];

export const RESOURCES: CatalogResource[] = ROWS.map(([slug, title, url, provider, type, difficulty, cost, minutes, description, why, tags]) => ({
	slug,
	title,
	url,
	provider,
	type,
	difficulty,
	cost,
	minutes,
	description,
	why,
	tags
}));

export const RESOURCE_BY_SLUG = new Map(RESOURCES.map((r) => [r.slug, r]));
